program: /home/morl-baselines/envelope_DST.py
method: bayes
metric:
  goal: maximize
  name: eval/hypervolume
parameters:
  learning_rate:
    distribution: uniform
    min: 0.0001
    max: 0.001
  epsilon_decay_steps:
    distribution: int_uniform
    min: 10000
    max: 100000
  target_net_update_freq:
    distribution: int_uniform
    min: 500
    max: 2000
  batch_size:
    distribution: categorical
    values: [8,16,32,64]
  seed:
    distribution: int_uniform
    min: 1
    max: 100
  homotopy_decay_steps:
    distribution: int_uniform
    min: 10000
    max: 200000
  buffer_size:
    distribution: int_uniform
    min: 100000
    max: 1000000