program: /home/morl-baselines/mp_mo_q_learning_DST.py
method: bayes
metric:
  goal: maximize
  name: eval/hypervolume
parameters:
  learning_rate:
    distribution: uniform
    min: 0.1
    max: 1.0
  epsilon_decay_steps:
    distribution: int_uniform
    min: 1000
    max: 10000
  seed:
    distribution: int_uniform
    min: 1
    max: 100

